name: Remind Slack for old PRs

on:
  schedule:
    - cron: "0 0 * * *" # This will run daily at midnight

jobs:
  remind_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check old PRs
        id: check_prs
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | \
          jq '[.[] | select(.created_at < (now | . - (2*7*24*60*60))) | .html_url]' > old_prs.json
      - name: Send Slack Reminder
        if: steps.check_prs.outputs.old_prs != '[]'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          status: custom
          fields: repo,message
          custom_payload: |
            {
              "text": "PRs open for more than 2 weeks: $(cat old_prs.json)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
